In [ ]:
# prompt: Mount google drive

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import os
from tqdm import tqdm

In [ ]:
# Load the dataset
df_athlete = pd.read_csv('/content/drive/MyDrive/ML files/2024_New dataset/athletes.csv')
medal_df = pd.read_csv('/content/drive/MyDrive/ML files/2024_New dataset/medallists.csv')
pd.set_option('display.max_rows', None)  # Shows all rows
pd.set_option('display.max_columns', None)  # Shows all columns

In [ ]:
df_athlete.head()

,code,current,name,name_short,name_tv,gender,function,country_code,country,country_long,nationality,nationality_long,nationality_code,height,weight,disciplines,events,birth_date,birth_place,birth_country,residence_place,residence_country,nickname,hobbies,occupation,education,family,lang,coach,reason,hero,influence,philosophy,sporting_relatives,ritual,other_sports
0,1532872,True,ALEKSANYAN Artur,ALEKSANYAN A,Artur ALEKSANYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,Armenia,ARM,0.0,0.0,['Wrestling'],"[""Men's Greco-Roman 97kg""]",10/21/1991,GYUMRI,Armenia,GYUMRI,Armenia,White Bear,Playing and watching football,Athlete,Graduated from Shirak State University (Gyumri...,"Father, Gevorg Aleksanyan","Armenian, English, Russian","Gevorg Aleksanyan (ARM), father",He followed his father and his uncle into the ...,"Footballer Zinedine Zidane (FRA), World Cup wi...","His father, Gevorg Aleksanyan","""Wrestling is my life."" (mediamax.am. 18 May 2...",NaN,NaN,NaN
1,1532873,True,AMOYAN Malkhas,AMOYAN M,Malkhas AMOYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,Armenia,ARM,0.0,0.0,['Wrestling'],"[""Men's Greco-Roman 77kg""]",1/22/1999,YEREVAN,Armenia,YEREVAN,Armenia,NaN,NaN,NaN,NaN,NaN,Armenian,NaN,NaN,NaN,NaN,"""To become a good athlete, you first have to b...","Uncle, Roman Amoyan (wrestling), 2008 Olympic ...",NaN,NaN
2,1532874,True,GALSTYAN Slavik,GALSTYAN S,Slavik GALSTYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,Armenia,ARM,0.0,0.0,['Wrestling'],"[""Men's Greco-Roman 67kg""]",12/21/1996,NaN,NaN,YEREVAN,Armenia,NaN,NaN,NaN,NaN,NaN,Armenian,Personal: Martin Alekhanyan (ARM).<br>National...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1532944,True,HARUTYUNYAN Arsen,HARUTYUNYAN A,Arsen HARUTYUNYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,Armenia,ARM,0.0,0.0,['Wrestling'],"[""Men's Freestyle 57kg""]",11/22/1999,MASIS,Armenia,YEREVAN,Armenia,NaN,NaN,Athlete,Graduated with a Master's degree from the Arme...,"Wife, Diana (married October 2022). Daughter, ...",Armenian,National: Habetnak Kurghinyan,While doing karate he noticed wrestlers traini...,"Wrestler Armen Nazaryan (ARM, BUL), two-time O...",NaN,"“Nothing is impossible, set goals in front of ...",NaN,NaN,NaN
4,1532945,True,TEVANYAN Vazgen,TEVANYAN V,Vazgen TEVANYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,Armenia,ARM,0.0,0.0,['Wrestling'],"[""Men's Freestyle 65kg""]",10/27/1999,POKR VEDI,Armenia,NaN,Armenia,NaN,NaN,Athlete,Studied at the Armenian State Institute of Phy...,"Wife, Sona (married November 2023)","Armenian, Russian",National: Habetnak Kurghinyan (ARM),“My family did not like wrestling very much. A...,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# prompt: Except the code, name, gender, country_code, country, height, weight, disciplines, events, birth_date columns drop every other column of df_athlete

columns_to_keep = ['code', 'name', 'gender', 'country_code', 'country', 'height', 'weight', 'disciplines', 'events', 'birth_date']
df_athlete = df_athlete[columns_to_keep]

In [ ]:
df_athlete.head()

,code,name,gender,country_code,country,height,weight,disciplines,events,birth_date
0,1532872,ALEKSANYAN Artur,Male,ARM,Armenia,0.0,0.0,['Wrestling'],"[""Men's Greco-Roman 97kg""]",10/21/1991
1,1532873,AMOYAN Malkhas,Male,ARM,Armenia,0.0,0.0,['Wrestling'],"[""Men's Greco-Roman 77kg""]",1/22/1999
2,1532874,GALSTYAN Slavik,Male,ARM,Armenia,0.0,0.0,['Wrestling'],"[""Men's Greco-Roman 67kg""]",12/21/1996
3,1532944,HARUTYUNYAN Arsen,Male,ARM,Armenia,0.0,0.0,['Wrestling'],"[""Men's Freestyle 57kg""]",11/22/1999
4,1532945,TEVANYAN Vazgen,Male,ARM,Armenia,0.0,0.0,['Wrestling'],"[""Men's Freestyle 65kg""]",10/27/1999

In [ ]:
# prompt: Except medal_type, medal_code, code_athlete columns drop every other column of medal_df

columns_to_drop = [col for col in medal_df.columns if col not in ['medal_type', 'medal_code', 'code_athlete']]
medal_df = medal_df.drop(columns=columns_to_drop)
medal_df.head()

     medal_type  medal_code  code_athlete
0    Gold Medal         1.0       1903136
1  Silver Medal         2.0       1923520
2  Bronze Medal         3.0       1903147
3    Gold Medal         1.0       1940173
4  Silver Medal         2.0       1912525

In [ ]:
# prompt: Now merge df_athlete and medal_df as a new table called df where the code column of the df_athlete is equal to code_athlete of the medal_df. Any missing value should be kept empty or NaN.

import pandas as pd
df = pd.merge(df_athlete, medal_df, left_on='code', right_on='code_athlete', how='outer')

In [ ]:
df.head()

,code,name,gender,country_code,country,height,weight,disciplines,events,birth_date,medal_type,medal_code,code_athlete
0,1532872,ALEKSANYAN Artur,Male,ARM,Armenia,0.0,0.0,['Wrestling'],"[""Men's Greco-Roman 97kg""]",10/21/1991,Silver Medal,2.0,1532872.0
1,1532873,AMOYAN Malkhas,Male,ARM,Armenia,0.0,0.0,['Wrestling'],"[""Men's Greco-Roman 77kg""]",1/22/1999,Bronze Medal,3.0,1532873.0
2,1532874,GALSTYAN Slavik,Male,ARM,Armenia,0.0,0.0,['Wrestling'],"[""Men's Greco-Roman 67kg""]",12/21/1996,NaN,NaN,NaN
3,1532944,HARUTYUNYAN Arsen,Male,ARM,Armenia,0.0,0.0,['Wrestling'],"[""Men's Freestyle 57kg""]",11/22/1999,NaN,NaN,NaN
4,1532945,TEVANYAN Vazgen,Male,ARM,Armenia,0.0,0.0,['Wrestling'],"[""Men's Freestyle 65kg""]",10/27/1999,NaN,NaN,NaN

In [ ]:
# Check for missing values
df.isnull().sum()

code               0
name               0
gender             0
country_code       0
country            0
height             3
weight             5
disciplines        0
events             0
birth_date         0
medal_type      9059
medal_code      9060
code_athlete    9059
dtype: int64

In [ ]:
backup1 = df.copy()

In [ ]:
# Check for duplicate rows
backup1.duplicated().sum()

119

In [ ]:
# Drop duplicate rows
backup1.drop_duplicates(inplace=True)

In [ ]:
# Display the count of each medal type
backup1['medal_type'].value_counts()

medal_type
Bronze Medal    768
Silver Medal    735
Gold Medal      693
Name: count, dtype: int64

In [ ]:
# Display the first few rows of the dataframe
backup1.head()

,code,name,gender,country_code,country,height,weight,disciplines,events,birth_date,medal_type,medal_code,code_athlete
0,1532872,ALEKSANYAN Artur,Male,ARM,Armenia,0.0,0.0,['Wrestling'],"[""Men's Greco-Roman 97kg""]",10/21/1991,Silver Medal,2.0,1532872.0
1,1532873,AMOYAN Malkhas,Male,ARM,Armenia,0.0,0.0,['Wrestling'],"[""Men's Greco-Roman 77kg""]",1/22/1999,Bronze Medal,3.0,1532873.0
2,1532874,GALSTYAN Slavik,Male,ARM,Armenia,0.0,0.0,['Wrestling'],"[""Men's Greco-Roman 67kg""]",12/21/1996,NaN,NaN,NaN
3,1532944,HARUTYUNYAN Arsen,Male,ARM,Armenia,0.0,0.0,['Wrestling'],"[""Men's Freestyle 57kg""]",11/22/1999,NaN,NaN,NaN
4,1532945,TEVANYAN Vazgen,Male,ARM,Armenia,0.0,0.0,['Wrestling'],"[""Men's Freestyle 65kg""]",10/27/1999,NaN,NaN,NaN

In [ ]:
# Create a backup of backup1
backup2 = backup1.copy()

# Print the first few rows of backup2 to verify
backup2.head()

,code,name,gender,country_code,country,height,weight,disciplines,events,birth_date,medal_type,medal_code,code_athlete
0,1532872,ALEKSANYAN Artur,Male,ARM,Armenia,0.0,0.0,['Wrestling'],"[""Men's Greco-Roman 97kg""]",10/21/1991,Silver Medal,2.0,1532872.0
1,1532873,AMOYAN Malkhas,Male,ARM,Armenia,0.0,0.0,['Wrestling'],"[""Men's Greco-Roman 77kg""]",1/22/1999,Bronze Medal,3.0,1532873.0
2,1532874,GALSTYAN Slavik,Male,ARM,Armenia,0.0,0.0,['Wrestling'],"[""Men's Greco-Roman 67kg""]",12/21/1996,NaN,NaN,NaN
3,1532944,HARUTYUNYAN Arsen,Male,ARM,Armenia,0.0,0.0,['Wrestling'],"[""Men's Freestyle 57kg""]",11/22/1999,NaN,NaN,NaN
4,1532945,TEVANYAN Vazgen,Male,ARM,Armenia,0.0,0.0,['Wrestling'],"[""Men's Freestyle 65kg""]",10/27/1999,NaN,NaN,NaN

In [ ]:
backup2.duplicated().sum()

0

In [ ]:
# prompt: Drop code, name, country, medal code, code_athlete columns from backup2

columns_to_drop = ['code', 'name', 'country', 'medal_code', 'code_athlete']
backup2 = backup2.drop(columns=columns_to_drop)

In [ ]:
backup2.duplicated().sum()

14

In [ ]:
# Drop duplicate rows
backup2.drop_duplicates(inplace=True)

In [ ]:
backup2.duplicated().sum()

0

In [ ]:
backup2.head()

,gender,country_code,height,weight,disciplines,events,birth_date,medal_type
0,Male,ARM,0.0,0.0,['Wrestling'],"[""Men's Greco-Roman 97kg""]",10/21/1991,Silver Medal
1,Male,ARM,0.0,0.0,['Wrestling'],"[""Men's Greco-Roman 77kg""]",1/22/1999,Bronze Medal
2,Male,ARM,0.0,0.0,['Wrestling'],"[""Men's Greco-Roman 67kg""]",12/21/1996,NaN
3,Male,ARM,0.0,0.0,['Wrestling'],"[""Men's Freestyle 57kg""]",11/22/1999,NaN
4,Male,ARM,0.0,0.0,['Wrestling'],"[""Men's Freestyle 65kg""]",10/27/1999,NaN

In [ ]:
# prompt: Add three new columns to backup2 after the country_code column called Year, Season, Host_City whose values for every row will be 2024, Summer, Paris respectively.

backup2.insert(backup2.columns.get_loc('country_code') + 1, 'Year', 2024)
backup2.insert(backup2.columns.get_loc('country_code') + 2, 'Season', 'Summer')
backup2.insert(backup2.columns.get_loc('country_code') + 3, 'Host_City', 'Paris')

backup2.head()

,gender,country_code,Year,Season,Host_City,height,weight,disciplines,events,birth_date,medal_type
0,Male,ARM,2024,Summer,Paris,0.0,0.0,['Wrestling'],"[""Men's Greco-Roman 97kg""]",10/21/1991,Silver Medal
1,Male,ARM,2024,Summer,Paris,0.0,0.0,['Wrestling'],"[""Men's Greco-Roman 77kg""]",1/22/1999,Bronze Medal
2,Male,ARM,2024,Summer,Paris,0.0,0.0,['Wrestling'],"[""Men's Greco-Roman 67kg""]",12/21/1996,NaN
3,Male,ARM,2024,Summer,Paris,0.0,0.0,['Wrestling'],"[""Men's Freestyle 57kg""]",11/22/1999,NaN
4,Male,ARM,2024,Summer,Paris,0.0,0.0,['Wrestling'],"[""Men's Freestyle 65kg""]",10/27/1999,NaN

In [ ]:
backup2.duplicated().sum()

0

In [ ]:
backup2.shape

(11241, 11)

In [ ]:
# prompt: Add a new column called Age after the gender column in backup2 where the value will be a whole integer value which will be the subtraction of birth_date column from the Year column

import pandas as pd
from datetime import datetime

# Convert 'birth_date' to datetime objects
backup2['birth_date'] = pd.to_datetime(backup2['birth_date'], errors='coerce')

# Calculate age based on the year and birth_date
backup2['Age'] = (backup2['Year'] - backup2['birth_date'].dt.year).astype('Int64')

# Reorder columns to place 'Age' after 'gender'
cols = backup2.columns.tolist()
age_index = cols.index('Age')
gender_index = cols.index('gender')
cols.insert(gender_index + 1, cols.pop(age_index))
backup2 = backup2[cols]

backup2.head()

,gender,Age,country_code,Year,Season,Host_City,height,weight,disciplines,events,birth_date,medal_type
0,Male,33,ARM,2024,Summer,Paris,0.0,0.0,['Wrestling'],"[""Men's Greco-Roman 97kg""]",1991-10-21,Silver Medal
1,Male,25,ARM,2024,Summer,Paris,0.0,0.0,['Wrestling'],"[""Men's Greco-Roman 77kg""]",1999-01-22,Bronze Medal
2,Male,28,ARM,2024,Summer,Paris,0.0,0.0,['Wrestling'],"[""Men's Greco-Roman 67kg""]",1996-12-21,NaN
3,Male,25,ARM,2024,Summer,Paris,0.0,0.0,['Wrestling'],"[""Men's Freestyle 57kg""]",1999-11-22,NaN
4,Male,25,ARM,2024,Summer,Paris,0.0,0.0,['Wrestling'],"[""Men's Freestyle 65kg""]",1999-10-27,NaN

In [ ]:
# prompt: Remove the third bracket, i.e., [ ] from the disciplines and events columns of backup2

backup2['disciplines'] = backup2['disciplines'].str.replace('[', '', regex=False).str.replace(']', '', regex=False)
backup2['events'] = backup2['events'].str.replace('[', '', regex=False).str.replace(']', '', regex=False)

backup2.head()

,gender,Age,country_code,Year,Season,Host_City,height,weight,disciplines,events,birth_date,medal_type
0,Male,33,ARM,2024,Summer,Paris,0.0,0.0,'Wrestling',"""Men's Greco-Roman 97kg""",1991-10-21,Silver Medal
1,Male,25,ARM,2024,Summer,Paris,0.0,0.0,'Wrestling',"""Men's Greco-Roman 77kg""",1999-01-22,Bronze Medal
2,Male,28,ARM,2024,Summer,Paris,0.0,0.0,'Wrestling',"""Men's Greco-Roman 67kg""",1996-12-21,NaN
3,Male,25,ARM,2024,Summer,Paris,0.0,0.0,'Wrestling',"""Men's Freestyle 57kg""",1999-11-22,NaN
4,Male,25,ARM,2024,Summer,Paris,0.0,0.0,'Wrestling',"""Men's Freestyle 65kg""",1999-10-27,NaN

In [ ]:
# prompt: Remove the single quotation i.e.,  ' ' , from the  disciplines column and double quotations , i.e., " ", from the events column of backup2

backup2['disciplines'] = backup2['disciplines'].str.replace("'", "")
backup2['events'] = backup2['events'].str.replace('"', "")

backup2.head()

,gender,Age,country_code,Year,Season,Host_City,height,weight,disciplines,events,birth_date,medal_type
0,Male,33,ARM,2024,Summer,Paris,0.0,0.0,Wrestling,Men's Greco-Roman 97kg,1991-10-21,Silver Medal
1,Male,25,ARM,2024,Summer,Paris,0.0,0.0,Wrestling,Men's Greco-Roman 77kg,1999-01-22,Bronze Medal
2,Male,28,ARM,2024,Summer,Paris,0.0,0.0,Wrestling,Men's Greco-Roman 67kg,1996-12-21,NaN
3,Male,25,ARM,2024,Summer,Paris,0.0,0.0,Wrestling,Men's Freestyle 57kg,1999-11-22,NaN
4,Male,25,ARM,2024,Summer,Paris,0.0,0.0,Wrestling,Men's Freestyle 65kg,1999-10-27,NaN

In [ ]:
# prompt: Merge the disciplines and events columns as a new column called Events by ensuring a space for backup2 and drop the two of them

# Combine 'disciplines' and 'events' into a new column 'Events'
backup2['Events'] = backup2['disciplines'] + ' ' + backup2['events']

# Drop the original 'disciplines' and 'events' columns
backup2 = backup2.drop(['disciplines', 'events'], axis=1)

backup2.head()

,gender,Age,country_code,Year,Season,Host_City,height,weight,birth_date,medal_type,Events
0,Male,33,ARM,2024,Summer,Paris,0.0,0.0,1991-10-21,Silver Medal,Wrestling Men's Greco-Roman 97kg
1,Male,25,ARM,2024,Summer,Paris,0.0,0.0,1999-01-22,Bronze Medal,Wrestling Men's Greco-Roman 77kg
2,Male,28,ARM,2024,Summer,Paris,0.0,0.0,1996-12-21,NaN,Wrestling Men's Greco-Roman 67kg
3,Male,25,ARM,2024,Summer,Paris,0.0,0.0,1999-11-22,NaN,Wrestling Men's Freestyle 57kg
4,Male,25,ARM,2024,Summer,Paris,0.0,0.0,1999-10-27,NaN,Wrestling Men's Freestyle 65kg

In [ ]:
# prompt: Drop the birth_rate column

backup2 = backup2.drop('birth_date', axis=1)
backup2.head()

,gender,Age,country_code,Year,Season,Host_City,height,weight,medal_type,Events
0,Male,33,ARM,2024,Summer,Paris,0.0,0.0,Silver Medal,Wrestling Men's Greco-Roman 97kg
1,Male,25,ARM,2024,Summer,Paris,0.0,0.0,Bronze Medal,Wrestling Men's Greco-Roman 77kg
2,Male,28,ARM,2024,Summer,Paris,0.0,0.0,NaN,Wrestling Men's Greco-Roman 67kg
3,Male,25,ARM,2024,Summer,Paris,0.0,0.0,NaN,Wrestling Men's Freestyle 57kg
4,Male,25,ARM,2024,Summer,Paris,0.0,0.0,NaN,Wrestling Men's Freestyle 65kg

In [ ]:
backup2.duplicated().sum()

376

In [ ]:
# Display the count of each medal type
backup2['medal_type'].value_counts()

medal_type
Bronze Medal    767
Silver Medal    735
Gold Medal      691
Name: count, dtype: int64

In [ ]:
# Create a backup of backup1
backup3 = backup2.copy()

# Print the first few rows of backup2 to verify
backup3.head()

,gender,Age,country_code,Year,Season,Host_City,height,weight,medal_type,Events
0,Male,33,ARM,2024,Summer,Paris,0.0,0.0,Silver Medal,Wrestling Men's Greco-Roman 97kg
1,Male,25,ARM,2024,Summer,Paris,0.0,0.0,Bronze Medal,Wrestling Men's Greco-Roman 77kg
2,Male,28,ARM,2024,Summer,Paris,0.0,0.0,NaN,Wrestling Men's Greco-Roman 67kg
3,Male,25,ARM,2024,Summer,Paris,0.0,0.0,NaN,Wrestling Men's Freestyle 57kg
4,Male,25,ARM,2024,Summer,Paris,0.0,0.0,NaN,Wrestling Men's Freestyle 65kg

In [ ]:
backup3.shape

(11241, 10)

In [ ]:
backup3.duplicated().sum()

376

In [ ]:
# Drop duplicate rows
backup3.drop_duplicates(inplace=True)

In [ ]:
backup3.duplicated().sum()

0

In [ ]:
backup3.head()

,gender,Age,country_code,Year,Season,Host_City,height,weight,medal_type,Events
0,Male,33,ARM,2024,Summer,Paris,0.0,0.0,Silver Medal,Wrestling Men's Greco-Roman 97kg
1,Male,25,ARM,2024,Summer,Paris,0.0,0.0,Bronze Medal,Wrestling Men's Greco-Roman 77kg
2,Male,28,ARM,2024,Summer,Paris,0.0,0.0,NaN,Wrestling Men's Greco-Roman 67kg
3,Male,25,ARM,2024,Summer,Paris,0.0,0.0,NaN,Wrestling Men's Freestyle 57kg
4,Male,25,ARM,2024,Summer,Paris,0.0,0.0,NaN,Wrestling Men's Freestyle 65kg

In [ ]:
# prompt: Find the count of the duplicates in backup3 using the country_code, Year, Season, Host_City, medal_type, Events columns

duplicates_count = backup3.duplicated(subset=['country_code', 'Year', 'Season', 'Host_City', 'medal_type', 'Events']).sum()
print(f"The number of duplicates based on specified columns is: {duplicates_count}")

The number of duplicates based on specified columns is: 4228

In [ ]:
# prompt: Drop these duplicates

backup3 = backup3.drop_duplicates(subset=['country_code', 'Year', 'Season', 'Host_City', 'medal_type', 'Events'])

In [ ]:
duplicates_count = backup3.duplicated(subset=['country_code', 'Year', 'Season', 'Host_City', 'medal_type', 'Events']).sum()
print(f"The number of duplicates based on specified columns is: {duplicates_count}")

The number of duplicates based on specified columns is: 0

In [ ]:
# Display the count of each medal type
backup3['medal_type'].value_counts()

medal_type
Bronze Medal    458
Silver Medal    408
Gold Medal      376
Name: count, dtype: int64

In [ ]:
backup3.head()

,gender,Age,country_code,Year,Season,Host_City,height,weight,medal_type,Events
0,Male,33,ARM,2024,Summer,Paris,0.0,0.0,Silver Medal,Wrestling Men's Greco-Roman 97kg
1,Male,25,ARM,2024,Summer,Paris,0.0,0.0,Bronze Medal,Wrestling Men's Greco-Roman 77kg
2,Male,28,ARM,2024,Summer,Paris,0.0,0.0,NaN,Wrestling Men's Greco-Roman 67kg
3,Male,25,ARM,2024,Summer,Paris,0.0,0.0,NaN,Wrestling Men's Freestyle 57kg
4,Male,25,ARM,2024,Summer,Paris,0.0,0.0,NaN,Wrestling Men's Freestyle 65kg

In [ ]:
# prompt: Remove the 'Medal" string from medal_type in backup3

backup3['medal_type'] = backup3['medal_type'].str.replace('Medal', '')
backup3.head()

,gender,Age,country_code,Year,Season,Host_City,height,weight,medal_type,Events
0,Male,33,ARM,2024,Summer,Paris,0.0,0.0,Silver,Wrestling Men's Greco-Roman 97kg
1,Male,25,ARM,2024,Summer,Paris,0.0,0.0,Bronze,Wrestling Men's Greco-Roman 77kg
2,Male,28,ARM,2024,Summer,Paris,0.0,0.0,NaN,Wrestling Men's Greco-Roman 67kg
3,Male,25,ARM,2024,Summer,Paris,0.0,0.0,NaN,Wrestling Men's Freestyle 57kg
4,Male,25,ARM,2024,Summer,Paris,0.0,0.0,NaN,Wrestling Men's Freestyle 65kg

In [ ]:
# Check for missing values
backup3.isnull().sum()

gender             0
Age                0
country_code       0
Year               0
Season             0
Host_City          0
height             3
weight             4
medal_type      5395
Events             0
dtype: int64

In [ ]:
# prompt: Rename the columns gender as Gender, country_code as NOC, height as Height, weight as Weight, medal_type as Medal in backup3

backup3 = backup3.rename(columns={
    'gender': 'Gender',
    'country_code': 'NOC',
    'height': 'Height',
    'weight': 'Weight',
    'medal_type': 'Medal'
})

backup3.head()

,Gender,Age,NOC,Year,Season,Host_City,Height,Weight,Medal,Events
0,Male,33,ARM,2024,Summer,Paris,0.0,0.0,Silver,Wrestling Men's Greco-Roman 97kg
1,Male,25,ARM,2024,Summer,Paris,0.0,0.0,Bronze,Wrestling Men's Greco-Roman 77kg
2,Male,28,ARM,2024,Summer,Paris,0.0,0.0,NaN,Wrestling Men's Greco-Roman 67kg
3,Male,25,ARM,2024,Summer,Paris,0.0,0.0,NaN,Wrestling Men's Freestyle 57kg
4,Male,25,ARM,2024,Summer,Paris,0.0,0.0,NaN,Wrestling Men's Freestyle 65kg

In [ ]:
# prompt: print a table for the USA medals

usa_medals = backup3[backup3['NOC'] == 'USA']
print(usa_medals)

       Gender  Age  NOC  Year  Season Host_City  Height  Weight    Medal  \
4772     Male   31  USA  2024  Summer     Paris   195.0     0.0  Bronze
4785   Female   19  USA  2024  Summer     Paris   175.0     0.0      NaN
5505   Female   26  USA  2024  Summer     Paris     0.0     0.0      NaN
5506     Male   34  USA  2024  Summer     Paris     0.0     0.0      NaN
5507     Male   20  USA  2024  Summer     Paris     0.0     0.0  Bronze
5508   Female   21  USA  2024  Summer     Paris     0.0     0.0    Gold
5509   Female   34  USA  2024  Summer     Paris     0.0     0.0      NaN
5525   Female   29  USA  2024  Summer     Paris   185.0     0.0  Silver
5550     Male   27  USA  2024  Summer     Paris   192.0     0.0  Bronze
5565     Male   29  USA  2024  Summer     Paris   203.0     0.0      NaN
5567   Female   29  USA  2024  Summer     Paris   188.0     0.0      NaN
6753   Female   26  USA  2024  Summer     Paris     0.0     0.0  Silver
6754   Female   33  USA  2024  Summer     Paris     0.0     0.0      NaN
6755     Male   31  USA  2024  Summer     Paris     0.0     0.0  Silver
6757   Female   33  USA  2024  Summer     Paris     0.0     0.0  Silver
6758   Female   22  USA  2024  Summer     Paris     0.0     0.0      NaN
6759     Male   27  USA  2024  Summer     Paris     0.0     0.0      NaN
6760     Male   23  USA  2024  Summer     Paris     0.0     0.0      NaN
6761   Female   19  USA  2024  Summer     Paris     0.0     0.0  Bronze
6762   Female   31  USA  2024  Summer     Paris   177.0     0.0      NaN
6763   Female   23  USA  2024  Summer     Paris   170.0     0.0      NaN
6764     Male   28  USA  2024  Summer     Paris   201.0     0.0      NaN
6765     Male   27  USA  2024  Summer     Paris   196.0     0.0  Bronze
6766   Female   20  USA  2024  Summer     Paris   175.0     0.0      NaN
6768     Male   34  USA  2024  Summer     Paris   188.0     0.0  Silver
6769   Female   30  USA  2024  Summer     Paris   170.0     0.0      NaN
6770     Male   27  USA  2024  Summer     Paris   185.0     0.0  Bronze
6773   Female   28  USA  2024  Summer     Paris     0.0     0.0      NaN
6774     Male   24  USA  2024  Summer     Paris     0.0     0.0      NaN
6775   Female   20  USA  2024  Summer     Paris     0.0     0.0      NaN
7120   Female   28  USA  2024  Summer     Paris     0.0     0.0  Silver
7121   Female   28  USA  2024  Summer     Paris     0.0     0.0    Gold
7122     Male   21  USA  2024  Summer     Paris     0.0     0.0    Gold
7123     Male   21  USA  2024  Summer     Paris     0.0     0.0  Silver
7124     Male   23  USA  2024  Summer     Paris     0.0     0.0    Gold
7125     Male   23  USA  2024  Summer     Paris     0.0     0.0  Silver
7126   Female   22  USA  2024  Summer     Paris     0.0     0.0      NaN
7127   Female   23  USA  2024  Summer     Paris     0.0     0.0  Bronze
7128   Female   23  USA  2024  Summer     Paris     0.0     0.0    Gold
7129   Female   26  USA  2024  Summer     Paris     0.0     0.0  Silver
7130     Male   25  USA  2024  Summer     Paris     0.0     0.0      NaN
7131     Male   23  USA  2024  Summer     Paris     0.0     0.0  Silver
7132   Female   21  USA  2024  Summer     Paris     0.0     0.0      NaN
7133   Female   23  USA  2024  Summer     Paris     0.0     0.0    Gold
7134   Female   23  USA  2024  Summer     Paris     0.0     0.0  Silver
7137     Male   28  USA  2024  Summer     Paris     0.0     0.0    Gold
7139     Male   28  USA  2024  Summer     Paris     0.0     0.0  Silver
7140     Male   22  USA  2024  Summer     Paris     0.0     0.0      NaN
7141     Male   31  USA  2024  Summer     Paris     0.0     0.0  Silver
7142     Male   31  USA  2024  Summer     Paris     0.0     0.0    Gold
7144     Male   25  USA  2024  Summer     Paris     0.0     0.0  Silver
7145     Male   25  USA  2024  Summer     Paris     0.0     0.0    Gold
7146     Male   23  USA  2024  Summer     Paris     0.0     0.0  Bronze
7147     Male   23  USA  2024  Summer     Paris     0.0     0.0  Silver
7148   Female   20  USA  2024  Summer     Paris     0.0     0.0  Silver
7149   Female   18  USA  2024  Summer     Paris     0.0     0.0  Silver
7150     Male   21  USA  2024  Summer     Paris     0.0     0.0    Gold
7151     Male   21  USA  2024  Summer     Paris     0.0     0.0  Silver
7152     Male   17  USA  2024  Summer     Paris     0.0     0.0  Silver
7153     Male   29  USA  2024  Summer     Paris     0.0     0.0    Gold
7154     Male   21  USA  2024  Summer     Paris     0.0     0.0  Bronze
7155     Male   21  USA  2024  Summer     Paris     0.0     0.0  Silver
7156   Female   22  USA  2024  Summer     Paris     0.0     0.0    Gold
7157   Female   22  USA  2024  Summer     Paris     0.0     0.0  Silver
7161     Male   23  USA  2024  Summer     Paris     0.0     0.0      NaN
7162     Male   20  USA  2024  Summer     Paris     0.0     0.0      NaN
7163     Male   30  USA  2024  Summer     Paris     0.0     0.0      NaN
7165   Female   27  USA  2024  Summer     Paris     0.0     0.0    Gold
7167   Female   27  USA  2024  Summer     Paris     0.0     0.0  Bronze
7168   Female   27  USA  2024  Summer     Paris     0.0     0.0    Gold
7170   Female   27  USA  2024  Summer     Paris     0.0     0.0  Silver
7171   Female   26  USA  2024  Summer     Paris     0.0     0.0  Bronze
7172   Female   26  USA  2024  Summer     Paris     0.0     0.0  Silver
7173   Female   28  USA  2024  Summer     Paris     0.0     0.0  Silver
7176     Male   29  USA  2024  Summer     Paris     0.0     0.0  Bronze
7177     Male   29  USA  2024  Summer     Paris     0.0     0.0    Gold
7178     Male   29  USA  2024  Summer     Paris     0.0     0.0  Silver
7179   Female   22  USA  2024  Summer     Paris     0.0     0.0  Silver
7181     Male   23  USA  2024  Summer     Paris     0.0     0.0      NaN
7182     Male   20  USA  2024  Summer     Paris     0.0     0.0      NaN
7183   Female   18  USA  2024  Summer     Paris     0.0     0.0  Silver
7184   Female   18  USA  2024  Summer     Paris     0.0     0.0    Gold
7185     Male   24  USA  2024  Summer     Paris     0.0     0.0  Silver
7186   Female   22  USA  2024  Summer     Paris     0.0     0.0  Silver
7189   Female   22  USA  2024  Summer     Paris     0.0     0.0    Gold
7193     Male   22  USA  2024  Summer     Paris     0.0     0.0      NaN
7194   Female   23  USA  2024  Summer     Paris     0.0     0.0      NaN
7195   Female   21  USA  2024  Summer     Paris     0.0     0.0  Silver
7197   Female   21  USA  2024  Summer     Paris     0.0     0.0    Gold
7199   Female   20  USA  2024  Summer     Paris     0.0     0.0    Gold
7201   Female   23  USA  2024  Summer     Paris     0.0     0.0  Bronze
7202     Male   18  USA  2024  Summer     Paris     0.0     0.0      NaN
7771   Female   28  USA  2024  Summer     Paris     0.0     0.0  Silver
7772   Female   21  USA  2024  Summer     Paris     0.0     0.0  Silver
7781     Male   26  USA  2024  Summer     Paris     0.0     0.0      NaN
7783   Female   22  USA  2024  Summer     Paris     0.0     0.0    Gold
7784   Female   19  USA  2024  Summer     Paris     0.0     0.0      NaN
7802   Female   21  USA  2024  Summer     Paris   172.0     0.0    Gold
7829     Male   22  USA  2024  Summer     Paris   185.0     0.0      NaN
7869     Male   28  USA  2024  Summer     Paris     0.0     0.0      NaN
7870     Male   17  USA  2024  Summer     Paris     0.0     0.0      NaN
7872   Female   28  USA  2024  Summer     Paris     0.0     0.0      NaN
7873     Male   23  USA  2024  Summer     Paris     0.0     0.0  Silver
7875     Male   30  USA  2024  Summer     Paris     0.0     0.0  Bronze
7876   Female   18  USA  2024  Summer     Paris     0.0     0.0      NaN
7878     Male   25  USA  2024  Summer     Paris     0.0     0.0  Silver
7882   Female   23  USA  2024  Summer     Paris     0.0     0.0      NaN
7883     Male   49  USA  2024  Summer     Paris     0.0     0.0      NaN
7884     Male   35  USA  2024  Summer     Paris     0.0     0.0    Gold
7885     Male   35  USA  2024  Summer     Paris     0.0     0.0  Silver
7886     Male   28  USA  2024  Summer     Paris     0.0     0.0      NaN
7887     Male   22  USA  2024  Summer     Paris     0.0     0.0      NaN
7888   Female   20  USA  2024  Summer     Paris     0.0     0.0      NaN
7889   Female   31  USA  2024  Summer     Paris     0.0     0.0      NaN
7891   Female   31  USA  2024  Summer     Paris     0.0     0.0  Silver
7893   Female   20  USA  2024  Summer     Paris     0.0     0.0      NaN
7896   Female   23  USA  2024  Summer     Paris     0.0     0.0  Bronze
7897   Female   23  USA  2024  Summer     Paris     0.0     0.0  Silver
7899   Female   23  USA  2024  Summer     Paris     0.0     0.0      NaN
7900   Female   29  USA  2024  Summer     Paris     0.0     0.0      NaN
7905   Female   24  USA  2024  Summer     Paris     0.0     0.0      NaN
7906     Male   28  USA  2024  Summer     Paris     0.0     0.0      NaN
7907   Female   32  USA  2024  Summer     Paris     0.0     0.0      NaN
7909     Male   27  USA  2024  Summer     Paris     0.0     0.0  Bronze
7910     Male   23  USA  2024  Summer     Paris     0.0     0.0      NaN
7911     Male   27  USA  2024  Summer     Paris     0.0     0.0    Gold
7918   Female   25  USA  2024  Summer     Paris     0.0     0.0      NaN
7921   Female   24  USA  2024  Summer     Paris     0.0     0.0      NaN
7928   Female   27  USA  2024  Summer     Paris     0.0     0.0      NaN
7930   Female   33  USA  2024  Summer     Paris     0.0     0.0      NaN
7937     Male   28  USA  2024  Summer     Paris     0.0     0.0      NaN
7945   Female   32  USA  2024  Summer     Paris     0.0     0.0      NaN
8621     Male   21  USA  2024  Summer     Paris   170.0     0.0      NaN
8622   Female   23  USA  2024  Summer     Paris   161.0     0.0      NaN
8624     Male   18  USA  2024  Summer     Paris   170.0     0.0      NaN
8625   Female   21  USA  2024  Summer     Paris   174.0     0.0      NaN
8627   Female   23  USA  2024  Summer     Paris   157.0     0.0  Silver
8628     Male   18  USA  2024  Summer     Paris   180.0     0.0  Bronze
8629     Male   29  USA  2024  Summer     Paris     0.0     0.0  Bronze
8630     Male   31  USA  2024  Summer     Paris     0.0     0.0      NaN
8631   Female   35  USA  2024  Summer     Paris     0.0     0.0      NaN
8633     Male   33  USA  2024  Summer     Paris     0.0     0.0      NaN
8634     Male   23  USA  2024  Summer     Paris     0.0     0.0      NaN
8636   Female   23  USA  2024  Summer     Paris     0.0     0.0      NaN
8638   Female   31  USA  2024  Summer     Paris     0.0     0.0      NaN
8639   Female   35  USA  2024  Summer     Paris     0.0     0.0      NaN
8641   Female   23  USA  2024  Summer     Paris     0.0     0.0      NaN
8643   Female   26  USA  2024  Summer     Paris   160.0    63.0  Bronze
8655     Male   38  USA  2024  Summer     Paris   185.0    80.0      NaN
8668   Female   20  USA  2024  Summer     Paris     0.0     0.0      NaN
8669   Female   26  USA  2024  Summer     Paris     0.0     0.0      NaN
8670   Female   26  USA  2024  Summer     Paris     0.0     0.0      NaN
8671     Male   35  USA  2024  Summer     Paris     0.0     0.0      NaN
8672     Male   29  USA  2024  Summer     Paris     0.0     0.0      NaN
8673     Male   24  USA  2024  Summer     Paris     0.0     0.0      NaN
8674   Female   30  USA  2024  Summer     Paris     0.0     0.0    Gold
8677   Female   31  USA  2024  Summer     Paris     0.0     0.0      NaN
8679     Male   25  USA  2024  Summer     Paris     0.0     0.0  Bronze
8682     Male   30  USA  2024  Summer     Paris     0.0     0.0      NaN
8685   Female   21  USA  2024  Summer     Paris     0.0     0.0  Silver
8689   Female   22  USA  2024  Summer     Paris     0.0     0.0    Gold
8714   Female   32  USA  2024  Summer     Paris     0.0     0.0      NaN
8715   Female   34  USA  2024  Summer     Paris     0.0     0.0      NaN
8716     Male   27  USA  2024  Summer     Paris     0.0     0.0      NaN
8717   Female   34  USA  2024  Summer     Paris     0.0     0.0      NaN
8718     Male   21  USA  2024  Summer     Paris     0.0     0.0      NaN
8724     Male   31  USA  2024  Summer     Paris   177.0     0.0      NaN
8725   Female   26  USA  2024  Summer     Paris   178.0     0.0      NaN
8728     Male   28  USA  2024  Summer     Paris   193.0     0.0    Gold
8731     Male   42  USA  2024  Summer     Paris     0.0     0.0      NaN
8732     Male   34  USA  2024  Summer     Paris     0.0     0.0  Silver
8733   Female   40  USA  2024  Summer     Paris     0.0     0.0      NaN
8734     Male   44  USA  2024  Summer     Paris     0.0     0.0  Silver
8740     Male   39  USA  2024  Summer     Paris     0.0     0.0      NaN
8931   Female   27  USA  2024  Summer     Paris     0.0     0.0      NaN
8946   Female   28  USA  2024  Summer     Paris     0.0     0.0  Silver
8947     Male   25  USA  2024  Summer     Paris     0.0     0.0      NaN
8948   Female   29  USA  2024  Summer     Paris     0.0     0.0  Silver
8949     Male   21  USA  2024  Summer     Paris     0.0     0.0      NaN
8951   Female   25  USA  2024  Summer     Paris     0.0     0.0      NaN
8952     Male   27  USA  2024  Summer     Paris     0.0     0.0      NaN
8953   Female   30  USA  2024  Summer     Paris     0.0     0.0      NaN
8954   Female   26  USA  2024  Summer     Paris     0.0     0.0      NaN
8955     Male   20  USA  2024  Summer     Paris     0.0     0.0      NaN
8956   Female   21  USA  2024  Summer     Paris     0.0     0.0      NaN
9023     Male   30  USA  2024  Summer     Paris   213.0     0.0    Gold
9035   Female   28  USA  2024  Summer     Paris   186.0     0.0    Gold
9039   Female   31  USA  2024  Summer     Paris   191.0     0.0  Bronze
9049     Male   30  USA  2024  Summer     Paris   198.0     0.0      NaN
9133     Male   22  USA  2024  Summer     Paris     0.0     0.0      NaN
9134   Female   25  USA  2024  Summer     Paris     0.0     0.0      NaN
9135   Female   26  USA  2024  Summer     Paris     0.0     0.0  Silver
9136   Female   29  USA  2024  Summer     Paris     0.0     0.0  Silver
9138     Male   22  USA  2024  Summer     Paris     0.0     0.0      NaN
9139   Female   21  USA  2024  Summer     Paris     0.0     0.0    Gold
9141   Female   27  USA  2024  Summer     Paris     0.0     0.0  Bronze
9142   Female   27  USA  2024  Summer     Paris     0.0     0.0    Gold
9144   Female   32  USA  2024  Summer     Paris     0.0     0.0    Gold
9146     Male   25  USA  2024  Summer     Paris     0.0     0.0      NaN
9147     Male   30  USA  2024  Summer     Paris     0.0     0.0      NaN
9148     Male   25  USA  2024  Summer     Paris     0.0     0.0      NaN
9149     Male   26  USA  2024  Summer     Paris     0.0     0.0      NaN
9150   Female   22  USA  2024  Summer     Paris     0.0     0.0      NaN
9151   Female   23  USA  2024  Summer     Paris     0.0     0.0      NaN
9155   Female   30  USA  2024  Summer     Paris     0.0     0.0    Gold
9161     Male   35  USA  2024  Summer     Paris     0.0     0.0      NaN
9162     Male   22  USA  2024  Summer     Paris     0.0     0.0      NaN
9163   Female   22  USA  2024  Summer     Paris     0.0     0.0  Silver
9164   Female   20  USA  2024  Summer     Paris     0.0     0.0  Bronze
9168     Male   24  USA  2024  Summer     Paris     0.0     0.0  Bronze
9169     Male   30  USA  2024  Summer     Paris     0.0     0.0      NaN
9170   Female   20  USA  2024  Summer     Paris     0.0     0.0    Gold
9171     Male   26  USA  2024  Summer     Paris     0.0     0.0      NaN
9172   Female   21  USA  2024  Summer     Paris     0.0     0.0  Silver
9173     Male   33  USA  2024  Summer     Paris     0.0     0.0  Bronze
9174     Male   22  USA  2024  Summer     Paris     0.0     0.0      NaN
9175   Female   31  USA  2024  Summer     Paris     0.0     0.0    Gold
9176     Male   26  USA  2024  Summer     Paris     0.0     0.0  Silver
9177   Female   33  USA  2024  Summer     Paris     0.0     0.0  Bronze
9178   Female   28  USA  2024  Summer     Paris     0.0     0.0      NaN
9179     Male   25  USA  2024  Summer     Paris     0.0     0.0      NaN
9180   Female   28  USA  2024  Summer     Paris     0.0     0.0      NaN
9181     Male   33  USA  2024  Summer     Paris     0.0     0.0      NaN
9182     Male   29  USA  2024  Summer     Paris     0.0     0.0      NaN
9183     Male   29  USA  2024  Summer     Paris     0.0     0.0      NaN
9191   Female   25  USA  2024  Summer     Paris   167.0     0.0      NaN
9192   Female   36  USA  2024  Summer     Paris     0.0     0.0      NaN
9194     Male   30  USA  2024  Summer     Paris     0.0     0.0      NaN
9195     Male   30  USA  2024  Summer     Paris     0.0     0.0  Bronze
9196     Male   36  USA  2024  Summer     Paris     0.0     0.0  Silver
9197     Male   36  USA  2024  Summer     Paris     0.0     0.0  Bronze
9198   Female   21  USA  2024  Summer     Paris     0.0     0.0      NaN
9199   Female   20  USA  2024  Summer     Paris     0.0     0.0  Bronze
9201     Male   26  USA  2024  Summer     Paris   182.0     0.0      NaN
9202   Female   23  USA  2024  Summer     Paris   176.0     0.0      NaN
9203     Male   34  USA  2024  Summer     Paris   185.0     0.0      NaN
9205     Male   21  USA  2024  Summer     Paris   185.0     0.0      NaN
9206   Female   34  USA  2024  Summer     Paris   169.0     0.0      NaN
9207     Male   24  USA  2024  Summer     Paris   190.0     0.0      NaN
9208   Female   27  USA  2024  Summer     Paris   163.0     0.0      NaN
9209     Male   22  USA  2024  Summer     Paris   171.0     0.0      NaN
9210     Male   30  USA  2024  Summer     Paris   175.0     0.0      NaN
9211     Male   22  USA  2024  Summer     Paris   180.0     0.0  Bronze
9212   Female   22  USA  2024  Summer     Paris   157.0     0.0      NaN
9213   Female   29  USA  2024  Summer     Paris   170.0     0.0      NaN
9214   Female   21  USA  2024  Summer     Paris   165.0     0.0      NaN
9443     Male   29  USA  2024  Summer     Paris     0.0     0.0      NaN
9444     Male   20  USA  2024  Summer     Paris     0.0     0.0  Bronze
9445   Female   24  USA  2024  Summer     Paris     0.0     0.0      NaN
9446     Male   20  USA  2024  Summer     Paris     0.0     0.0  Bronze
9447   Female   16  USA  2024  Summer     Paris     0.0     0.0    Gold
9448   Female   24  USA  2024  Summer     Paris     0.0     0.0  Bronze
9450   Female   24  USA  2024  Summer     Paris     0.0     0.0      NaN
9452   Female   23  USA  2024  Summer     Paris     0.0     0.0    Gold
9456   Female   27  USA  2024  Summer     Paris     0.0     0.0  Silver
9460   Female   21  USA  2024  Summer     Paris     0.0     0.0  Bronze
9485     Male   32  USA  2024  Summer     Paris   187.0     0.0  Silver
9486     Male   32  USA  2024  Summer     Paris   187.0     0.0    Gold
9487   Female   28  USA  2024  Summer     Paris   170.0     0.0    Gold
9488     Male   27  USA  2024  Summer     Paris   172.0     0.0      NaN
9489     Male   28  USA  2024  Summer     Paris   175.0     0.0      NaN
9490   Female   30  USA  2024  Summer     Paris   162.0     0.0      NaN
9493     Male   30  USA  2024  Summer     Paris   187.0     0.0      NaN
9494     Male   23  USA  2024  Summer     Paris   193.0     0.0      NaN
9495     Male   30  USA  2024  Summer     Paris   183.0     0.0      NaN
9496   Female   28  USA  2024  Summer     Paris   165.0     0.0      NaN
9497   Female   26  USA  2024  Summer     Paris   165.0     0.0      NaN
9498   Female   24  USA  2024  Summer     Paris   162.0     0.0    Gold
9499     Male   27  USA  2024  Summer     Paris   177.0     0.0    Gold
9500     Male   27  USA  2024  Summer     Paris   177.0     0.0  Bronze
9501     Male   26  USA  2024  Summer     Paris   187.0     0.0    Gold
9503     Male   32  USA  2024  Summer     Paris   185.0     0.0  Silver
9504   Female   29  USA  2024  Summer     Paris   175.0     0.0  Silver
9505   Female   29  USA  2024  Summer     Paris   175.0     0.0    Gold

In [ ]:
# prompt: print the counts of the gold, silver, bronze medals of USA separately

gold_count = len(usa_medals[usa_medals['Medal'] == 'Gold'])
silver_count = len(usa_medals[usa_medals['Medal'] == 'Silver'])
bronze_count = len(usa_medals[usa_medals['Medal'] == 'Bronze'])

print(f"USA Gold Medals: {gold_count}")
print(f"USA Silver Medals: {silver_count}")
print(f"USA Bronze Medals: {bronze_count}")

USA Gold Medals: 0
USA Silver Medals: 0
USA Bronze Medals: 0

In [ ]:
# prompt: why is it showing 0 counts even though there are medals for USA?

# Check the unique values in the 'Medal' column for USA
print(usa_medals['Medal'].unique())

# Check the unique values in the 'NOC' column for USA
print(usa_medals['NOC'].unique())

# Inspect the rows where 'Medal' is not null and 'NOC' is 'USA'
print(backup3[(backup3['Medal'].notnull()) & (backup3['NOC'] == 'USA')])

['Bronze ' nan 'Gold ' 'Silver ']
['USA']
       Gender  Age  NOC  Year  Season Host_City  Height  Weight    Medal  \
4772     Male   31  USA  2024  Summer     Paris   195.0     0.0  Bronze
5507     Male   20  USA  2024  Summer     Paris     0.0     0.0  Bronze
5508   Female   21  USA  2024  Summer     Paris     0.0     0.0    Gold
5525   Female   29  USA  2024  Summer     Paris   185.0     0.0  Silver
5550     Male   27  USA  2024  Summer     Paris   192.0     0.0  Bronze
6753   Female   26  USA  2024  Summer     Paris     0.0     0.0  Silver
6755     Male   31  USA  2024  Summer     Paris     0.0     0.0  Silver
6757   Female   33  USA  2024  Summer     Paris     0.0     0.0  Silver
6761   Female   19  USA  2024  Summer     Paris     0.0     0.0  Bronze
6765     Male   27  USA  2024  Summer     Paris   196.0     0.0  Bronze
6768     Male   34  USA  2024  Summer     Paris   188.0     0.0  Silver
6770     Male   27  USA  2024  Summer     Paris   185.0     0.0  Bronze
7120   Female   28  USA  2024  Summer     Paris     0.0     0.0  Silver
7121   Female   28  USA  2024  Summer     Paris     0.0     0.0    Gold
7122     Male   21  USA  2024  Summer     Paris     0.0     0.0    Gold
7123     Male   21  USA  2024  Summer     Paris     0.0     0.0  Silver
7124     Male   23  USA  2024  Summer     Paris     0.0     0.0    Gold
7125     Male   23  USA  2024  Summer     Paris     0.0     0.0  Silver
7127   Female   23  USA  2024  Summer     Paris     0.0     0.0  Bronze
7128   Female   23  USA  2024  Summer     Paris     0.0     0.0    Gold
7129   Female   26  USA  2024  Summer     Paris     0.0     0.0  Silver
7131     Male   23  USA  2024  Summer     Paris     0.0     0.0  Silver
7133   Female   23  USA  2024  Summer     Paris     0.0     0.0    Gold
7134   Female   23  USA  2024  Summer     Paris     0.0     0.0  Silver
7137     Male   28  USA  2024  Summer     Paris     0.0     0.0    Gold
7139     Male   28  USA  2024  Summer     Paris     0.0     0.0  Silver
7141     Male   31  USA  2024  Summer     Paris     0.0     0.0  Silver
7142     Male   31  USA  2024  Summer     Paris     0.0     0.0    Gold
7144     Male   25  USA  2024  Summer     Paris     0.0     0.0  Silver
7145     Male   25  USA  2024  Summer     Paris     0.0     0.0    Gold
7146     Male   23  USA  2024  Summer     Paris     0.0     0.0  Bronze
7147     Male   23  USA  2024  Summer     Paris     0.0     0.0  Silver
7148   Female   20  USA  2024  Summer     Paris     0.0     0.0  Silver
7149   Female   18  USA  2024  Summer     Paris     0.0     0.0  Silver
7150     Male   21  USA  2024  Summer     Paris     0.0     0.0    Gold
7151     Male   21  USA  2024  Summer     Paris     0.0     0.0  Silver
7152     Male   17  USA  2024  Summer     Paris     0.0     0.0  Silver
7153     Male   29  USA  2024  Summer     Paris     0.0     0.0    Gold
7154     Male   21  USA  2024  Summer     Paris     0.0     0.0  Bronze
7155     Male   21  USA  2024  Summer     Paris     0.0     0.0  Silver
7156   Female   22  USA  2024  Summer     Paris     0.0     0.0    Gold
7157   Female   22  USA  2024  Summer     Paris     0.0     0.0  Silver
7165   Female   27  USA  2024  Summer     Paris     0.0     0.0    Gold
7167   Female   27  USA  2024  Summer     Paris     0.0     0.0  Bronze
7168   Female   27  USA  2024  Summer     Paris     0.0     0.0    Gold
7170   Female   27  USA  2024  Summer     Paris     0.0     0.0  Silver
7171   Female   26  USA  2024  Summer     Paris     0.0     0.0  Bronze
7172   Female   26  USA  2024  Summer     Paris     0.0     0.0  Silver
7173   Female   28  USA  2024  Summer     Paris     0.0     0.0  Silver
7176     Male   29  USA  2024  Summer     Paris     0.0     0.0  Bronze
7177     Male   29  USA  2024  Summer     Paris     0.0     0.0    Gold
7178     Male   29  USA  2024  Summer     Paris     0.0     0.0  Silver
7179   Female   22  USA  2024  Summer     Paris     0.0     0.0  Silver
7183   Female   18  USA  2024  Summer     Paris     0.0     0.0  Silver
7184   Female   18  USA  2024  Summer     Paris     0.0     0.0    Gold
7185     Male   24  USA  2024  Summer     Paris     0.0     0.0  Silver
7186   Female   22  USA  2024  Summer     Paris     0.0     0.0  Silver
7189   Female   22  USA  2024  Summer     Paris     0.0     0.0    Gold
7195   Female   21  USA  2024  Summer     Paris     0.0     0.0  Silver
7197   Female   21  USA  2024  Summer     Paris     0.0     0.0    Gold
7199   Female   20  USA  2024  Summer     Paris     0.0     0.0    Gold
7201   Female   23  USA  2024  Summer     Paris     0.0     0.0  Bronze
7771   Female   28  USA  2024  Summer     Paris     0.0     0.0  Silver
7772   Female   21  USA  2024  Summer     Paris     0.0     0.0  Silver
7783   Female   22  USA  2024  Summer     Paris     0.0     0.0    Gold
7802   Female   21  USA  2024  Summer     Paris   172.0     0.0    Gold
7873     Male   23  USA  2024  Summer     Paris     0.0     0.0  Silver
7875     Male   30  USA  2024  Summer     Paris     0.0     0.0  Bronze
7878     Male   25  USA  2024  Summer     Paris     0.0     0.0  Silver
7884     Male   35  USA  2024  Summer     Paris     0.0     0.0    Gold
7885     Male   35  USA  2024  Summer     Paris     0.0     0.0  Silver
7891   Female   31  USA  2024  Summer     Paris     0.0     0.0  Silver
7896   Female   23  USA  2024  Summer     Paris     0.0     0.0  Bronze
7897   Female   23  USA  2024  Summer     Paris     0.0     0.0  Silver
7909     Male   27  USA  2024  Summer     Paris     0.0     0.0  Bronze
7911     Male   27  USA  2024  Summer     Paris     0.0     0.0    Gold
8627   Female   23  USA  2024  Summer     Paris   157.0     0.0  Silver
8628     Male   18  USA  2024  Summer     Paris   180.0     0.0  Bronze
8629     Male   29  USA  2024  Summer     Paris     0.0     0.0  Bronze
8643   Female   26  USA  2024  Summer     Paris   160.0    63.0  Bronze
8674   Female   30  USA  2024  Summer     Paris     0.0     0.0    Gold
8679     Male   25  USA  2024  Summer     Paris     0.0     0.0  Bronze
8685   Female   21  USA  2024  Summer     Paris     0.0     0.0  Silver
8689   Female   22  USA  2024  Summer     Paris     0.0     0.0    Gold
8728     Male   28  USA  2024  Summer     Paris   193.0     0.0    Gold
8732     Male   34  USA  2024  Summer     Paris     0.0     0.0  Silver
8734     Male   44  USA  2024  Summer     Paris     0.0     0.0  Silver
8946   Female   28  USA  2024  Summer     Paris     0.0     0.0  Silver
8948   Female   29  USA  2024  Summer     Paris     0.0     0.0  Silver
9023     Male   30  USA  2024  Summer     Paris   213.0     0.0    Gold
9035   Female   28  USA  2024  Summer     Paris   186.0     0.0    Gold
9039   Female   31  USA  2024  Summer     Paris   191.0     0.0  Bronze
9135   Female   26  USA  2024  Summer     Paris     0.0     0.0  Silver
9136   Female   29  USA  2024  Summer     Paris     0.0     0.0  Silver
9139   Female   21  USA  2024  Summer     Paris     0.0     0.0    Gold
9141   Female   27  USA  2024  Summer     Paris     0.0     0.0  Bronze
9142   Female   27  USA  2024  Summer     Paris     0.0     0.0    Gold
9144   Female   32  USA  2024  Summer     Paris     0.0     0.0    Gold
9155   Female   30  USA  2024  Summer     Paris     0.0     0.0    Gold
9163   Female   22  USA  2024  Summer     Paris     0.0     0.0  Silver
9164   Female   20  USA  2024  Summer     Paris     0.0     0.0  Bronze
9168     Male   24  USA  2024  Summer     Paris     0.0     0.0  Bronze
9170   Female   20  USA  2024  Summer     Paris     0.0     0.0    Gold
9172   Female   21  USA  2024  Summer     Paris     0.0     0.0  Silver
9173     Male   33  USA  2024  Summer     Paris     0.0     0.0  Bronze
9175   Female   31  USA  2024  Summer     Paris     0.0     0.0    Gold
9176     Male   26  USA  2024  Summer     Paris     0.0     0.0  Silver
9177   Female   33  USA  2024  Summer     Paris     0.0     0.0  Bronze
9195     Male   30  USA  2024  Summer     Paris     0.0     0.0  Bronze
9196     Male   36  USA  2024  Summer     Paris     0.0     0.0  Silver
9197     Male   36  USA  2024  Summer     Paris     0.0     0.0  Bronze
9199   Female   20  USA  2024  Summer     Paris     0.0     0.0  Bronze
9211     Male   22  USA  2024  Summer     Paris   180.0     0.0  Bronze
9444     Male   20  USA  2024  Summer     Paris     0.0     0.0  Bronze
9446     Male   20  USA  2024  Summer     Paris     0.0     0.0  Bronze
9447   Female   16  USA  2024  Summer     Paris     0.0     0.0    Gold
9448   Female   24  USA  2024  Summer     Paris     0.0     0.0  Bronze
9452   Female   23  USA  2024  Summer     Paris     0.0     0.0    Gold
9456   Female   27  USA  2024  Summer     Paris     0.0     0.0  Silver
9460   Female   21  USA  2024  Summer     Paris     0.0     0.0  Bronze
9485     Male   32  USA  2024  Summer     Paris   187.0     0.0  Silver
9486     Male   32  USA  2024  Summer     Paris   187.0     0.0    Gold
9487   Female   28  USA  2024  Summer     Paris   170.0     0.0    Gold
9498   Female   24  USA  2024  Summer     Paris   162.0     0.0    Gold
9499     Male   27  USA  2024  Summer     Paris   177.0     0.0    Gold
9500     Male   27  USA  2024  Summer     Paris   177.0     0.0  Bronze
9501     Male   26  USA  2024  Summer     Paris   187.0     0.0    Gold
9503     Male   32  USA  2024  Summer     Paris   185.0     0.0  Silver
9504   Female   29  USA  2024  Summer     Paris   175.0     0.0  Silver
9505   Female   29  USA  2024  Summer     Paris   175.0     0.0    Gold
9506   Female   24  USA  2024  Summer     Paris   157.0     0.0  Silver
9507   Female   24  USA  2024  Summer     Paris   157.0     0.0    Gold
9529   Female   27  USA  2024  Summer     Paris   180.0     0.0  Silver
9530   Female   29  USA  2024  Summer     Paris   162.0     0.0  Bronze
9541     Male   26  USA  2024  Summer     Paris   187.0     0.0  Silver
9545     Male   27  USA  2024  Summer     Paris   190.0     0.0    Gold
9547     Male   32  USA  2024  Summer     Paris   200.0     0.0    Gold
9550   Female   25  USA  2024  Summer     Paris   160.0     0.0    Gold
9552   Female   29  USA  2024  Summer     Paris   185.0     0.0    Gold
9576   Female   28  USA  2024  Summer     Paris   182.0     0.0  Silver
9579   Female   24  USA  2024  Summer     Paris   177.0     0.0    Gold
9585     Male   23  USA  2024  Summer     Paris   177.0     0.0    Gold
9587     Male   29  USA  2024  Summer     Paris   190.0     0.0  Bronze
9588     Male   27  USA  2024  Summer     Paris   177.0     0.0  Bronze
9590     Male   27  USA  2024  Summer     Paris   187.0     0.0    Gold
9595   Female   23  USA  2024  Summer     Paris   162.0     0.0  Bronze
9597   Female   32  USA  2024  Summer     Paris   172.0     0.0    Gold
9886     Male   26  USA  2024  Summer     Paris   177.0     0.0    Gold
9890     Male   27  USA  2024  Summer     Paris   185.0     0.0  Silver
9894     Male   35  USA  2024  Summer     Paris   182.0     0.0  Silver
9895   Female   23  USA  2024  Summer     Paris   172.0     0.0  Bronze
9899   Female   33  USA  2024  Summer     Paris   173.0     0.0  Silver
9909     Male   28  USA  2024  Summer     Paris   187.0     0.0  Silver
9910   Female   25  USA  2024  Summer     Paris   175.0     0.0    Gold
9913     Male   25  USA  2024  Summer     Paris   185.0     0.0  Bronze
9983   Female   28  USA  2024  Summer     Paris   177.0     0.0    Gold
9991     Male   25  USA  2024  Summer     Paris   180.0     0.0  Silver
11358  Female   22  USA  2024  Summer     Paris   167.0     0.0  Silver

                                                  Events
4772                                    Water Polo 'Men'
5507                            Weightlifting Men's 61kg
5508                          Weightlifting Women's 71kg
5525                                  Volleyball 'Women'
5550                                    Volleyball 'Men'
6753   Cycling Road, Triathlon Women's Individual Tim...
6755                          Triathlon Men's Individual
6757                        Triathlon Women's Individual
6761                             Taekwondo 'Women -67kg'
6765   Tennis Men's Doubles, Men's Singles, 'Mixed Do...
6768                                Tennis Men's Doubles
6770                 Tennis Men's Doubles, Men's Singles
7120   Swimming Women's 4 x 100m Freestyle Relay, 'Re...
7121   Swimming Women's 4 x 100m Freestyle Relay, 'Re...
7122   Swimming Men's 100m Freestyle, Men's 4 x 100m ...
7123   Swimming Men's 100m Freestyle, Men's 4 x 100m ...
7124   Swimming Men's 100m Backstroke, Men's 4 x 100m...
7125   Swimming Men's 100m Backstroke, Men's 4 x 100m...
7127   Swimming Women's 100m Backstroke, Women's 4 x ...
7128   Swimming Women's 100m Backstroke, Women's 4 x ...
7129   Swimming Women's 4 x 100m Freestyle Relay, 'Re...
7131   Swimming Men's 4 x 200m Freestyle Relay, 'Rela...
7133   Swimming Women's 200m Breaststroke, Women's 20...
7134   Swimming Women's 200m Breaststroke, Women's 20...
7137   Swimming Men's 100m Butterfly, Men's 4 x 100m ...
7139   Swimming Men's 100m Butterfly, Men's 4 x 100m ...
7141   Swimming Men's 100m Breaststroke, Men's 4 x 10...
7142   Swimming Men's 100m Breaststroke, Men's 4 x 10...
7144   Swimming Men's 1500m Freestyle, Men's 800m Fre...
7145   Swimming Men's 1500m Freestyle, Men's 800m Fre...
7146   Swimming Men's 200m Individual Medley, Men's 4...
7147   Swimming Men's 200m Individual Medley, Men's 4...
7148   Swimming Women's 200m Freestyle, Women's 4 x 2...
7149   Marathon Swimming, Swimming Women's 10km, Wome...
7150   Swimming Men's 100m Freestyle, Men's 200m Free...
7151   Swimming Men's 100m Freestyle, Men's 200m Free...
7152   Swimming Men's 100m Butterfly, Men's 200m Butt...
7153   Swimming Men's 4 x 100m Freestyle Relay, 'Rela...
7154   Swimming Men's 200m Freestyle, Men's 4 x 200m ...
7155   Swimming Men's 200m Freestyle, Men's 4 x 200m ...
7156   Swimming Women's 100m Butterfly, Women's 100m ...
7157   Swimming Women's 100m Butterfly, Women's 100m ...
7165   Swimming Women's 100m Breaststroke, Women's 20...
7167   Swimming Women's 1500m Freestyle, Women's 400m...
7168   Swimming Women's 1500m Freestyle, Women's 400m...
7170   Swimming Women's 1500m Freestyle, Women's 400m...
7171   Swimming Women's 400m Freestyle, Women's 4 x 2...
7172   Swimming Women's 400m Freestyle, Women's 4 x 2...
7173   Swimming Women's 4 x 100m Freestyle Relay, Wom...
7176   Swimming Men's 100m Backstroke, Men's 200m Bac...
7177   Swimming Men's 100m Backstroke, Men's 200m Bac...
7178   Swimming Men's 100m Backstroke, Men's 200m Bac...
7179   Swimming Women's 4 x 200m Freestyle Relay, 'Re...
7183   Swimming Women's 200m Butterfly, Women's 4 x 1...
7184   Swimming Women's 200m Butterfly, Women's 4 x 1...
7185   Swimming Men's 400m Freestyle, Men's 4 x 200m ...
7186   Swimming Women's 100m Backstroke, Women's 200m...
7189   Swimming Women's 100m Backstroke, Women's 200m...
7195   Swimming Women's 100m Butterfly, Women's 100m ...
7197   Swimming Women's 100m Butterfly, Women's 100m ...
7199   Swimming Women's 100m Breaststroke, Women's 4 ...
7201             Swimming Women's 400m Individual Medley
7771                            Artistic Swimming 'Team'
7772                    Artistic Swimming 'Team', 'Duet'
7783                                     Surfing 'Women'
7802                                    Football 'Women'
7873                          Skateboarding Men's Street
7875                          Skateboarding Men's Street
7878                            Skateboarding Men's Park
7884            Shooting 'Skeet Men', 'Skeet Mixed Team'
7885            Shooting 'Skeet Men', 'Skeet Mixed Team'
7891   Shooting '10m Air Rifle Women', '50m Rifle 3 P...
7896          Shooting 'Skeet Women', 'Skeet Mixed Team'
7897          Shooting 'Skeet Women', 'Skeet Mixed Team'
7909                                  Rowing Men's Eight
7911                                   Rowing Men's Four
8627               Sport Climbing Women's Boulder & Lead
8628                          Sport Climbing Men's Speed
8629                                 Sailing Men's Skiff
8643                                Rugby Sevens 'Women'
8674   Fencing Women's Foil Individual, Women's Foil ...
8679      Fencing Men's Foil Individual, Men's Foil Team
8685   Fencing Women's Foil Individual, Women's Foil ...
8689                           Fencing Women's Foil Team
8728                   Golf Men's Individual Stroke Play
8732                           Equestrian 'Jumping Team'
8734     Equestrian 'Jumping Individual', 'Jumping Team'
8946   Diving Women's 3m Springboard, Women's Synchro...
8948          Diving Women's Synchronised 3m Springboard
9023                                    Basketball 'Men'
9035                                  Basketball 'Women'
9039                              3x3 Basketball 'Women'
9135         Cycling Mountain Bike Women's Cross-country
9136                  Cycling BMX Freestyle Women's Park
9139                  Cycling Track Women's Team Pursuit
9141   Cycling Road, Cycling Track Women's Road Race,...
9142   Cycling Road, Cycling Track Women's Road Race,...
9144   Cycling Road, Cycling Track Women's Road Race,...
9155   Cycling Track Women's Madison, Women's Omnium,...
9163              Canoe Sprint Women's Canoe Single 200m
9164   Canoe Slalom Women's Canoe Single, Women's Kay...
9168                      Wrestling Men's Freestyle 86kg
9170                    Wrestling Women's Freestyle 68kg
9172                    Wrestling Women's Freestyle 76kg
9173                      Wrestling Men's Freestyle 74kg
9175                    Wrestling Women's Freestyle 50kg
9176                      Wrestling Men's Freestyle 57kg
9177                    Wrestling Women's Freestyle 57kg
9195                                   Breaking 'B-Boys'
9196              Archery Men's Individual, 'Mixed Team'
9197              Archery Men's Individual, 'Mixed Team'
9199   Archery Women's Individual, Women's Team, 'Mix...
9211                                   Boxing Men's 71kg
9444   Artistic Gymnastics 'Men', Men's Floor Exercis...
9446   Artistic Gymnastics 'Men', Men's All-Around, M...
9447   Artistic Gymnastics 'Women', Women's Balance B...
9448   Artistic Gymnastics 'Women', Women's Balance B...
9452   Artistic Gymnastics 'Women', Women's All-Aroun...
9456   Artistic Gymnastics 'Women', Women's All-Aroun...
9460   Artistic Gymnastics 'Women', Women's All-Aroun...
9485   Athletics Men's 4 x 400m Relay, '4 x 400m Rela...
9486   Athletics Men's 4 x 400m Relay, '4 x 400m Rela...
9487                    Athletics Women's 4 x 100m Relay
9498                      Athletics Women's 100m Hurdles
9499   Athletics Men's 100m, Men's 200m, Men's 4 x 10...
9500   Athletics Men's 100m, Men's 200m, Men's 4 x 10...
9501          Athletics Men's 400m, Men's 4 x 400m Relay
9503                          Athletics Men's Pole Vault
9504   Athletics Women's 4 x 400m Relay, '4 x 400m Re...
9505   Athletics Women's 4 x 400m Relay, '4 x 400m Re...
9506      Athletics Women's 100m, Women's 4 x 100m Relay
9507      Athletics Women's 100m, Women's 4 x 100m Relay
9529                      Athletics Women's 400m Hurdles
9530                              Athletics Women's 200m
9541   Athletics Men's 100m, Men's 200m, Men's 4 x 10...
9545   Athletics Men's 400m Hurdles, Men's 4 x 400m R...
9547                            Athletics Men's Shot Put
9550                         Athletics Women's Long Jump
9552                      Athletics Women's Discus Throw
9576                      Athletics Women's Hammer Throw
9579      Athletics Women's 400m, Women's 4 x 400m Relay
9585                               Athletics Men's 1500m
9587          Athletics Men's 100m, Men's 4 x 100m Relay
9588                Athletics Men's 10,000m, Men's 5000m
9590                        Athletics Men's 110m Hurdles
9595      Athletics Women's 100m, Women's 4 x 100m Relay
9597                    Athletics Women's 4 x 400m Relay
9886   Athletics Men's 4 x 100m Relay, Men's 4 x 400m...

In [ ]:
# prompt: Ok, now print them as a count

usa_medal_counts = usa_medals['Medal'].value_counts()
print(usa_medal_counts)

Medal
Silver     63
Gold       54
Bronze     41
Name: count, dtype: int64

In [ ]:
backup3.shape

(6637, 10)

In [ ]:
# prompt: Rearrange the columns of backup3 in the following order: 	Gender, Age, Height, Weight, NOC, Year, Season, Host_City, Event, Medal

new_column_order = ['Gender', 'Age', 'Height', 'Weight', 'NOC', 'Year', 'Season', 'Host_City', 'Events', 'Medal']
backup3 = backup3[new_column_order]
backup3.head()

,Gender,Age,Height,Weight,NOC,Year,Season,Host_City,Events,Medal
0,Male,33,0.0,0.0,ARM,2024,Summer,Paris,Wrestling Men's Greco-Roman 97kg,Silver
1,Male,25,0.0,0.0,ARM,2024,Summer,Paris,Wrestling Men's Greco-Roman 77kg,Bronze
2,Male,28,0.0,0.0,ARM,2024,Summer,Paris,Wrestling Men's Greco-Roman 67kg,NaN
3,Male,25,0.0,0.0,ARM,2024,Summer,Paris,Wrestling Men's Freestyle 57kg,NaN
4,Male,25,0.0,0.0,ARM,2024,Summer,Paris,Wrestling Men's Freestyle 65kg,NaN

In [ ]:
# prompt: Replace the values of the Height and Weight Columns which have 0 or 0.0 in them with empty, i.e., NaN

import numpy as np
# Replace 0 and 0.0 in 'Height' and 'Weight' columns with NaN
backup3['Height'] = backup3['Height'].replace([0, 0.0], np.nan)
backup3['Weight'] = backup3['Weight'].replace([0, 0.0], np.nan)

backup3.head()

,Gender,Age,Height,Weight,NOC,Year,Season,Host_City,Events,Medal
0,Male,33,NaN,NaN,ARM,2024,Summer,Paris,Wrestling Men's Greco-Roman 97kg,Silver
1,Male,25,NaN,NaN,ARM,2024,Summer,Paris,Wrestling Men's Greco-Roman 77kg,Bronze
2,Male,28,NaN,NaN,ARM,2024,Summer,Paris,Wrestling Men's Greco-Roman 67kg,NaN
3,Male,25,NaN,NaN,ARM,2024,Summer,Paris,Wrestling Men's Freestyle 57kg,NaN
4,Male,25,NaN,NaN,ARM,2024,Summer,Paris,Wrestling Men's Freestyle 65kg,NaN

In [ ]:
backup3.isnull().sum()

Gender          0
Age             0
Height       4449
Weight       6613
NOC             0
Year            0
Season          0
Host_City       0
Events          0
Medal        5395
dtype: int64

In [ ]:
# prompt: print backup3 as a .csv file and make it downloadable

from google.colab import files

backup3.to_csv('backup3.csv', encoding = 'utf-8-sig')
files.download('backup3.csv')